services:
  - type: web
    name: sbermobile-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
      - key: WEBHOOK_URL
      - key: PORT
        value: "8000"
